"""Apply the 'needs-dub' label to titles Plex can't play in a target language,
and keep it in sync (remove it once a title becomes watchable).

Plex has no per-title hide API, so the *hide* is done downstream: this labels the
items and (optionally) writes a Kometa fragment that builds a smart collection on
the label, which your existing Kometa run turns into the hidden/surfaced row.
"""

from __future__ import annotations

import logging
from pathlib import Path

from .clients.plex import TYPE_NUM, PlexClient

log = logging.getLogger("doblarr.plex_labels")


def _primary_sections(plex: PlexClient) -> tuple[list[dict], list[dict]]:
    """Main movie + show libraries (prefer titles 'Movies' / 'TV Shows',
    otherwise the first of each type — avoids side libraries like 'YouTube')."""
    secs = plex.sections()
    movies = [s for s in secs if s["type"] == "movie"]
    shows = [s for s in secs if s["type"] == "show"]
    movie_primary = next((s for s in movies if s["title"].lower() == "movies"), None) \
        or (movies[0] if movies else None)
    show_primary = next((s for s in shows if s["title"].lower() == "tv shows"), None) \
        or (shows[0] if shows else None)
    return ([movie_primary] if movie_primary else [],
            [show_primary] if show_primary else [])


def find_item(plex: PlexClient, title: str, year: int | None = None,
              source: str = "") -> dict | None:
    """Best Plex match for a title — movies first for Radarr-sourced titles,
    shows first for Sonarr-sourced, both when unknown. For shows this matches
    the series (per-episode refresh isn't available via title matching)."""
    movie_secs, show_secs = _primary_sections(plex)
    secs = (show_secs + movie_secs) if source.startswith("Sonarr") \
        else (movie_secs + show_secs)
    for s in secs:
        found = plex.find(s["key"], TYPE_NUM[s["type"]], title, year)
        if found:
            found["section"] = s
            return found
    return None


def sync_labels(items: list, plex: PlexClient, config, apply: bool = False) -> dict:
    """Add the needs-dub label to needs-dub/partial titles and remove it elsewhere."""
    f = config.get("filtering", {}) or {}
    label = f.get("tag_missing_dub", "needs-dub")
    movie_secs, show_secs = _primary_sections(plex)

    needs = [i for i in items if i.status in ("needs-dub", "partial")]
    needs_keys = {(i.title.strip().lower(), i.year) for i in needs}

    report = {"label": label, "apply": apply, "matched": 0, "added": 0,
              "removed": 0, "unmatched": []}

    # 1) Add the label to titles that need a dub.
    for i in needs:
        secs = movie_secs if i.source.startswith("Radarr") else show_secs
        found = None
        for s in secs:
            found = plex.find(s["key"], TYPE_NUM[s["type"]], i.title, i.year)
            if found:
                found["section"] = s
                break
        if not found:
            report["unmatched"].append(f"{i.title} ({i.year})")
            continue
        report["matched"] += 1
        already = any(lbl.lower() == label.lower() for lbl in found["labels"])
        if not already:
            if apply:
                plex.add_label(found["section"]["key"],
                               TYPE_NUM[found["section"]["type"]], found["ratingKey"], label)
            report["added"] += 1

    # 2) Remove the label from anything that no longer needs a dub.
    for s in movie_secs + show_secs:
        for it in plex.items_with_label(s["key"], TYPE_NUM[s["type"]], label):
            if (str(it["title"]).strip().lower(), it["year"]) not in needs_keys:
                if apply:
                    plex.remove_label(s["key"], TYPE_NUM[s["type"]], it["ratingKey"], label)
                report["removed"] += 1

    if apply and f.get("kometa_handoff", True):
        report["kometa_file"] = str(write_kometa_fragment(config))

    return report


def write_kometa_fragment(config) -> Path:
    """Write a Kometa collection file that hides/surfaces the labelled titles."""
    f = config.get("filtering", {}) or {}
    label = f.get("tag_missing_dub", "needs-dub")
    hidden = f.get("hidden_collection_name", "Not in your language")
    out = Path(f.get("kometa_file") or (config.output_dir / "doblarr-kometa.yml"))
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(
        "# Generated by Doblarr — include under your Movies and TV Shows Kometa libraries.\n"
        "collections:\n"
        f"  {hidden}:\n"
        "    smart_filter:\n"
        "      all:\n"
        f"        label: {label}\n"
        "    collection_order: alpha\n"
        "    visible_home: false\n"
        "    visible_shelf: false\n",
        encoding="utf-8",
    )
    return out
